# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsystem', '0002_auto_20180405_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='/%Y/%M/%d/%h/%m/s', max_length=50, verbose_name='\u56fe\u7247\u540d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='composite_img',
            field=models.ImageField(default='composite/default.png', upload_to='composite/%Y/%M'),
        ),
        migrations.AlterField(
            model_name='image',
            name='orginal_img',
            field=models.ImageField(default='original/default.png', upload_to='original/%Y/%M'),
        ),
        migrations.AlterField(
            model_name='image',
            name='processed_img',
            field=models.ImageField(default='processed/default.png', upload_to='processed/%Y/%M'),
        ),
    ]
