# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppsystem', '0003_auto_20180405_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageData',
        ),
    ]
