# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsystem', '0004_auto_20180405_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='composite_img',
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='orginal_img',
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='processed_img',
        ),
        migrations.AddField(
            model_name='imagedata',
            name='cu_composite_img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='cu_js_draw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='cu_original_img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='cu_processed_js',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='se_composite_img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='se_js_draw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='se_original_img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='se_processed_js',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
