# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsystem', '0005_auto_20180410_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='se_js_draw',
            field=models.ImageField(null=True, upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='se_processed_js',
            field=models.ImageField(null=True, upload_to='pro/%Y/%m'),
        ),
    ]
