# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsystem', '0007_auto_20180411_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='defects',
            field=models.TextField(null=True, verbose_name='\u7f3a\u9677'),
        ),
    ]
